In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [101]:
from google.colab import files
files.upload()

Saving Carseats.csv to Carseats (2).csv


{'Carseats.csv': b'Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US\r\n0,139,24,0,358,185,Medium,79,15,No,No\r\n0.16,102,33,0,217,139,Medium,70,18,No,No\r\n0.37,147,58,7,100,191,Bad,27,15,Yes,Yes\r\n0.53,122,88,7,36,159,Bad,28,17,Yes,Yes\r\n0.91,93,91,0,22,117,Bad,75,11,Yes,No\r\n1.42,99,32,18,341,108,Bad,80,16,Yes,Yes\r\n1.82,139,45,0,146,133,Bad,77,17,Yes,Yes\r\n2.05,131,82,0,132,157,Bad,25,14,Yes,No\r\n2.07,119,98,0,18,126,Bad,73,17,No,No\r\n2.23,111,25,0,52,121,Bad,43,18,No,No\r\n2.34,116,83,15,170,144,Bad,71,11,Yes,Yes\r\n2.52,124,61,0,333,138,Medium,76,16,Yes,No\r\n2.66,136,65,4,133,150,Bad,53,13,Yes,Yes\r\n2.67,115,54,0,406,128,Medium,42,17,Yes,Yes\r\n2.86,121,86,10,496,145,Bad,51,10,Yes,Yes\r\n2.93,143,21,5,81,160,Medium,67,12,No,Yes\r\n2.99,103,74,0,359,97,Bad,55,11,Yes,Yes\r\n3.02,98,21,11,326,90,Bad,76,11,No,Yes\r\n3.07,118,83,13,276,104,Bad,75,10,Yes,Yes\r\n3.13,130,62,11,396,130,Bad,66,14,Yes,Yes\r\n3.15,117,66,1,65,111,Bad,55,11,Yes,Yes

In [102]:
df = pd.read_csv('Carseats.csv')
df.head

<bound method NDFrame.head of      Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Educ

In [103]:
df.shape

(400, 11)

In [104]:
df.isnull().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB


In [106]:
df['ShelveLoc']=df['ShelveLoc'].astype('category')
df['ShelveLoc']=df['ShelveLoc'].cat.codes
df['ShelveLoc']

0      0
1      1
2      2
3      2
4      0
      ..
395    1
396    2
397    2
398    0
399    1
Name: ShelveLoc, Length: 400, dtype: int8

In [107]:
df['US']=df['US'].astype('category')
df['US']=df['US'].cat.codes
df['US']

0      1
1      1
2      1
3      1
4      0
      ..
395    1
396    1
397    1
398    1
399    1
Name: US, Length: 400, dtype: int8

In [108]:
df['Urban']=df['Urban'].astype('category')
df['Urban']=df['Urban'].cat.codes
df['Urban']

0      1
1      1
2      1
3      1
4      1
      ..
395    1
396    0
397    1
398    1
399    1
Name: Urban, Length: 400, dtype: int8

In [109]:
x = df.drop(columns = 'Sales')
y = df['Sales']
y

0       9.50
1      11.22
2      10.06
3       7.40
4       4.15
       ...  
395    12.57
396     6.14
397     7.41
398     5.94
399     9.71
Name: Sales, Length: 400, dtype: float64

In [110]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=181)

In [111]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# xtrain_scaled = scaler.fit_transform(xtrain)
# xtest_scaled = scaler.transform(xtest)

In [112]:
# from sklearn.tree import DecisionTreeClassifier
# DTC = DecisionTreeClassifier()
# DTC.fit(xtrain,ytrain)

DecisionTreeRegressor

In [113]:
from sklearn.tree import DecisionTreeRegressor
DTR = DecisionTreeRegressor()
DTR.fit(xtrain,ytrain)

DecisionTreeRegressor()

In [114]:
DTR.score(xtest,ytest)

0.5794091322758432

In [115]:
# score=[]
# for i in range(400):
#     xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state =i)
#     DTR1 = DecisionTreeRegressor()
#     DTR1.fit(xtrain,ytrain)
#     score.append(DTR1.score(xtest,ytest))
# np.argmax(score)

In [116]:
predict_value = np.array([[141,64,3,340,128,0,38,13,1,0]])
pred = DTR.predict(predict_value)
pred

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([4.56])

In [117]:
if pred>8:
  print('Yes')
else:
  print('NO')

NO


RandomForestRegressor

In [118]:
from sklearn.ensemble import RandomForestRegressor
RFR=RandomForestRegressor()
RFR.fit(xtrain,ytrain)

RandomForestRegressor()

In [119]:
RFR.score(xtest,ytest)

0.6894976608756518

In [120]:
RFR.predict([[141,64,3,340,128,0,38,13,1,0]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([5.6304])

KNN algorithm


In [121]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(xtrain,ytrain)

LinearRegression()

In [122]:
LR.score(xtest,ytest)

0.5903009274399456

In [123]:
LR.predict([[141,64,3,340,128,0,38,13,1,0]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7.55890557])