In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv('ageglucos.csv')

In [4]:
df

age  glucos
0   43    99.0
1   21    65.0
2   25    79.0
3   42    75.0
4   57    87.0
5   59    81.0
6   55     NaN

In [5]:
X = df[['age']]
Y = df['glucos']

In [6]:
df.glucos

0    99.0
1    65.0
2    79.0
3    75.0
4    87.0
5    81.0
6     NaN
Name: glucos, dtype: float64

In [7]:
nan_value_fit = df.glucos.median() # nan value fill up with median function
df.glucos = df.glucos.fillna(nan_value_fit)

In [8]:
df.glucos

0    99.0
1    65.0
2    79.0
3    75.0
4    87.0
5    81.0
6    80.0
Name: glucos, dtype: float64

In [9]:
xtrain, xtest, ytrain, ytest = train_test_split(X.values,Y,test_size=0.2,random_state=1)

In [10]:
reg = LinearRegression()

In [11]:
reg.fit(xtrain,ytrain)
reg.predict(xtest)

array([86.42105263, 72.21052632])

In [12]:
reg.predict([[55]])

array([86.42105263])

In [13]:
# print(reg.score(X,Y)*100,"%")

In [14]:
reg.coef_

array([0.47368421])

In [15]:
reg.intercept_

60.36842105263159

In [16]:
reg.score(X,Y)

F:\anaconda\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').